# Info
FROM		pgolm/gitlab-ci-runner
MAINTAINER	pgolm "golm.peter@gmail.com"

# Config
ENV			GITLAB_SERVER_FQDN gitlab.example.com
ENV 		GITLAB_CI_URL https://gitlab-ci.example.com
ENV 		GITLAB_CI_REGISTRATION_TOKEN <token>
ENV			HOME /root

# Init
RUN 		cd gitlab-ci-runner && CI_SERVER_URL=$GITLAB_CI_URL REGISTRATION_TOKEN=$GITLAB_CI_REGISTRATION_TOKEN bundle exec ./bin/setup
RUN 		ssh-keyscan -H $GITLAB_SERVER_FQDN >> /root/.ssh/known_hosts

# Install deps
RUN 		apt-get update -y
RUN 		apt-get install -y -q build-essential

WORKDIR 	/gitlab-ci-runner
CMD 		bundle exec ./bin/runner